name: "Hackage, Cabal, macOS"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "45 02 * * *"


jobs:

  build10:
    name: "GHC"
    runs-on: macos-latest
    # Template to build matrix of builds for subprojects in monorepo
    strategy:
      matrix:
        packageRoots: [ ./ ]
        ghc: [ "8.10" ]
    defaults:
      run:
        working-directory: "${{ matrix.packageRoots }}"
    steps:
      - uses: actions/checkout@v2
      - name: "Cache of ~/.cabal/packages, ~/.cabal/store and dist-newstyle"
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: "${{ runner.os }}-Cabal-${{ matrix.ghc }}"
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: "cabal v2-configure --disable-optimization --enable-tests --enable-deterministic"
      - run: "cabal v2-build"
      - run: "cabal v2-test"
