name: "Hackage, Cabal, Linux"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "45 02 * * *"

env:
  cabalConfig: --enable-tests --enable-benchmarks --disable-optimization --enable-deterministic

jobs:

  build10:
    name: "GHC"
    runs-on: ubuntu-latest
    # Template to build matrix of builds for subprojects in monorepo
    strategy:
      matrix:
        packageRoots: [ ./ ]
        ghc: [ "8.10", "8.4" ]
    defaults:
      run:
        working-directory: ${{ matrix.packageRoots }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Haskell env setup"
        id: HaskEnvSetup
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: "Repository update"
        run: cabal v2-update
      # NOTE: Freeze is for the caching
      - name: "Configuration freeze"
        run: cabal v2-freeze $cabalConfig
      - name: "Configuring GitHub cache"
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.HaskEnvSetup.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-Cabal-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-Cabal-${{ matrix.ghc }}-
      - name: "Build"
        run: cabal v2-build $cabalConfig
      - name: "Tests"
        run: cabal v2-test $cabalConfig
      - name: "Haddock"
        if: ${{ matrix.ghc == '8.10' }}
        run: cabal v2-haddock $cabalConfig
      - name: "Source distribution file"
        if: ${{ matrix.ghc == '8.10' }}
        run: cabal v2-sdist
