name: "Nixpkgs, Linux, GHCJS"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Every day at 05:45
    - cron: "45 05 * * *"

env:
  useRev: "true"
  rev: "nixos-unstable"
  cachixAccount: "haskell-with-nixpkgs"
  linkWithGold: "true"

jobs:
  build10:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v10
    - name: Install Cachix
      uses: cachix/cachix-action@v6
      with:
        name: ${{ env.cachixAccount }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Determined Nix-build
      run: ./ghcjs-build.sh
