name: "Direct import & build inside Nixpkgs"

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build10:
    name: "Integration test"
    runs-on: ubuntu-latest
    steps:
    - name: "Git checkout"
      uses: actions/checkout@v2
    - name: "Install Nix"
      uses: cachix/install-nix-action@v11
      with:
        nix_path: "nixpkgs=channel:nixos-unstable"
    - name: "Run Nixpkgs integration test"
      uses: Anton-Latukha/test-haskell-nixpkgs-integration-action@v1
